// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjwYP8mSXIZb-SU5Il4nA2G2rQ1WuFBM',
    appId: '1:575046042727:web:d7732b64a35b6dc37bc0c2',
    messagingSenderId: '575046042727',
    projectId: 'firecheck-1ec4c',
    authDomain: 'firecheck-1ec4c.firebaseapp.com',
    storageBucket: 'firecheck-1ec4c.firebasestorage.app',
    measurementId: 'G-DRC35F0ZF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtjwY7NHdPYk__P8oJ49bbzDYRtmIbWqY',
    appId: '1:575046042727:android:3a4f38bbb7e2e6317bc0c2',
    messagingSenderId: '575046042727',
    projectId: 'firecheck-1ec4c',
    storageBucket: 'firecheck-1ec4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABf_ofcyMAZrnDMNzhpZyNZdhs4vb7XFY',
    appId: '1:575046042727:ios:071ce40e1a86d2207bc0c2',
    messagingSenderId: '575046042727',
    projectId: 'firecheck-1ec4c',
    storageBucket: 'firecheck-1ec4c.firebasestorage.app',
    iosBundleId: 'com.example.firecheck',
  );
}
